In [4]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[58, 99, 89, 79],
       [64, 58, 62, 55],
       [32, 53, 33, 23],
       [41, 32,  9, 58],
       [92, 32, 54,  1],
       [46, 93, 24, 76]], dtype=int32)

In [10]:
np.sort(a)[::-1]

array([88, 86, 85, 74, 73, 71, 65, 54, 51, 51, 45, 42, 35, 28,  8],
      dtype=int32)

In [9]:
np.sort(b,axis = 0)

array([[32, 32,  9,  1],
       [41, 32, 24, 23],
       [46, 53, 33, 55],
       [58, 58, 54, 58],
       [64, 93, 62, 76],
       [92, 99, 89, 79]], dtype=int32)

In [11]:
# np.append

a

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [12]:
np.append(a,200)

array([ 85,  71,  51,   8,  28,  35,  45,  51,  88,  54,  86,  42,  74,
        73,  65, 200])

In [13]:
b

array([[58, 99, 89, 79],
       [64, 58, 62, 55],
       [32, 53, 33, 23],
       [41, 32,  9, 58],
       [92, 32, 54,  1],
       [46, 93, 24, 76]], dtype=int32)

In [18]:
np.append(b,np.ones((b.shape[0],1)),axis =1)

array([[58., 99., 89., 79.,  1.],
       [64., 58., 62., 55.,  1.],
       [32., 53., 33., 23.,  1.],
       [41., 32.,  9., 58.,  1.],
       [92., 32., 54.,  1.,  1.],
       [46., 93., 24., 76.,  1.]])

In [20]:
s=(b.shape[0],1)
s

(6, 1)

In [22]:
# concatenate

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
# np.unique

e = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,5,5,5,5,6,6,6,6])

In [24]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [25]:
# np.expand_dim

a.shape

(15,)

In [26]:
a

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [29]:
np.expand_dims(a , axis = 1)

array([[85],
       [71],
       [51],
       [ 8],
       [28],
       [35],
       [45],
       [51],
       [88],
       [54],
       [86],
       [42],
       [74],
       [73],
       [65]], dtype=int32)

In [33]:
# np.where)
(np.where(a>50))

(array([ 0,  1,  2,  7,  8,  9, 10, 12, 13, 14]),)

In [35]:
# replace all the value > 50 with 0
# np.where(condition, True, False)
np.where(a>50,True,a)

array([ 1,  1,  1,  8, 28, 35, 45,  1,  1,  1,  1, 42,  1,  1,  1],
      dtype=int32)

In [36]:
np.where(a%2 ==0,0,a)

array([85, 71, 51,  0,  0, 35, 45, 51,  0,  0,  0,  0,  0, 73, 65],
      dtype=int32)

In [37]:
# np.argmax
a

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [38]:
np.argmax(a)

np.int64(8)

In [39]:
b

array([[58, 99, 89, 79],
       [64, 58, 62, 55],
       [32, 53, 33, 23],
       [41, 32,  9, 58],
       [92, 32, 54,  1],
       [46, 93, 24, 76]], dtype=int32)

In [41]:
np.argmax(b, axis = 1)

array([1, 0, 1, 3, 0, 1])

In [42]:
np.argmin(a)

np.int64(3)

In [43]:
 np.argmin(b, axis = 0)

array([2, 3, 3, 4])

In [44]:
# np.cumsum

np.cumsum(a)

array([ 85, 156, 207, 215, 243, 278, 323, 374, 462, 516, 602, 644, 718,
       791, 856])

In [45]:
np.cumsum(b,axis = 0)

array([[ 58,  99,  89,  79],
       [122, 157, 151, 134],
       [154, 210, 184, 157],
       [195, 242, 193, 215],
       [287, 274, 247, 216],
       [333, 367, 271, 292]])

In [46]:
np.cumsum(b, axis = 1)

array([[ 58, 157, 246, 325],
       [ 64, 122, 184, 239],
       [ 32,  85, 118, 141],
       [ 41,  73,  82, 140],
       [ 92, 124, 178, 179],
       [ 46, 139, 163, 239]])

In [47]:
np.cumprod(a)

array([                  85,                 6035,               307785,
                    2462280,             68943840,           2413034400,
               108586548000,        5537913948000,      487336427424000,
          26316167080896000,  2263190368957056000,  2820275127648593920,
        5786174635190882304, -1884365326385278976,  6643462300923727872])

In [49]:
np.cumprod(b ,axis = 0)

array([[         58,          99,          89,          79],
       [       3712,        5742,        5518,        4345],
       [     118784,      304326,      182094,       99935],
       [    4870144,     9738432,     1638846,     5796230],
       [  448053248,   311629824,    88497684,     5796230],
       [20610449408, 28981573632,  2123944416,   440513480]])

In [50]:
a 

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [53]:
np.percentile(a,50)

np.float64(54.0)

In [55]:
np.histogram(a, bins = [0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

In [56]:
salary = np.array([20000,40000,250000,350000,60000])
experiance = np.array([1,3,2,4,2])

np.corrcoef(salary,experiance)

array([[1.        , 0.64257262],
       [0.64257262, 1.        ]])

In [58]:
# np.isin
np.isin(a,10)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [59]:
a

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [60]:
np.flip(a)

array([65, 73, 74, 42, 86, 54, 88, 51, 45, 35, 28,  8, 51, 71, 85],
      dtype=int32)

In [61]:
np.flip(a,axis = 0)

array([65, 73, 74, 42, 86, 54, 88, 51, 45, 35, 28,  8, 51, 71, 85],
      dtype=int32)

In [62]:
a 

array([85, 71, 51,  8, 28, 35, 45, 51, 88, 54, 86, 42, 74, 73, 65],
      dtype=int32)

In [63]:
np.put(a,[0,1],[110,710])

In [64]:
np.delete(a,[0,2,4])

array([710,   8,  35,  45,  51,  88,  54,  86,  42,  74,  73,  65],
      dtype=int32)

In [65]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [66]:
np.intersect1d(m,n)

array([3, 4, 5])

In [67]:
np.setdiff1d(n,m)

array([6, 7])

In [69]:
np.setxor1d(m,n)


array([1, 2, 6, 7])

In [70]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 51, 25, 28, 35, 45, 51, 75, 54, 75, 42, 74, 73, 65],
      dtype=int32)