# Creatng Numpy Array

In [5]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(type(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [10]:
# data type
a =np.array([1,2,3],dtype = float)
print(a)

[1. 2. 3.]


In [11]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# np.random
np.random.random((3,4))

array([[0.62545948, 0.42997104, 0.54907446, 0.08775912],
       [0.26028203, 0.29925206, 0.04858971, 0.9228352 ],
       [0.61854554, 0.71647864, 0.835346  , 0.31454721]])

In [20]:
# np.linspace
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [22]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print('one dimension =',a1)
print('two dimension =',a2)
print('three dimension=',a3)

one dimension = [0 1 2 3 4 5 6 7 8 9]
two dimension = [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
three dimension= [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [29]:
a1.ndim

1

In [30]:
a2.ndim

2

In [31]:
a3.ndim

3

In [35]:
print(a1.shape)

(10,)


In [36]:
print(a2.shape)

(3, 4)


In [34]:
a3.shape

(2, 2, 2)

In [37]:
a1.size

10

In [38]:
a2.size

12

In [39]:
a3.size

8

In [45]:
a1.itemsize

4

In [42]:
a2.itemsize

8

In [43]:
a3.itemsize

8

In [46]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [48]:
# changeing type
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [54]:
# Array operation
a1 = np.arange(12).reshape(3,4)
print('A1','=',a1)
a2 = np.arange(12,24).reshape(3,4)
print('A2','=',a2)

A1 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A2 = [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [55]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
# relational operators

a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [60]:
# vector operations
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [61]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [66]:
# Array Function

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[41., 43., 17.],
       [77., 29., 56.],
       [ 5., 93., 76.]])

In [71]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.max(a1)
np.sum(a1)
np.min(a1)
np.prod(a1)

np.float64(132447732906720.0)

In [73]:
np.max(a1,axis = 0)

array([77., 93., 76.])

In [75]:
# mean/ median/ std / var
np.mean(a1, axis = 1)

array([33.66666667, 54.        , 58.        ])

In [77]:
np.median(a1, axis = 0)

array([41., 43., 56.])

In [80]:
np.std(a1, axis =0)

array([29.39387691, 27.47119704, 24.4994331 ])

In [82]:
np.var(a1,axis = 0)

array([864.        , 754.66666667, 600.22222222])

In [83]:
np.sin(a1)

array([[-0.15862267, -0.83177474, -0.96139749],
       [ 0.99952016, -0.66363388, -0.521551  ],
       [-0.95892427, -0.94828214,  0.56610764]])

In [85]:
# dot products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [86]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [87]:
# log and experiments
np.log(a1)

array([[3.71357207, 3.76120012, 2.83321334],
       [4.34380542, 3.36729583, 4.02535169],
       [1.60943791, 4.53259949, 4.33073334]])

In [88]:
np.exp(a1)

array([[6.39843494e+17, 4.72783947e+18, 2.41549528e+07],
       [2.75851345e+33, 3.93133430e+12, 2.09165950e+24],
       [1.48413159e+02, 2.45124554e+40, 1.01480039e+33]])

In [92]:
np.round(np.random.random((2,3))*100)

array([[94., 94., 84.],
       [55., 15.,  3.]])

In [93]:
np.floor(np.random.random((2,3))*100)

array([[85., 71., 25.],
       [89., 47., 67.]])

In [95]:
np.ceil(np.random.random((2,3))*100)

array([[48.,  7., 85.],
       [ 1., 84., 22.]])

In [96]:
# indexing / slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a1[-1]

np.int64(9)

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[1,2]

np.int64(6)

In [102]:
a2[2,3]

np.int64(11)

In [103]:
a2[1,0]

np.int64(4)

In [104]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [105]:
a3[1,0,1]

np.int64(5)

In [106]:
a3[0,1,0]

np.int64(2)

In [107]:
a3[0,0,0]

np.int64(0)

In [108]:
a3[1,1,0]

np.int64(6)

In [109]:
# slicing

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a1[2:5]

array([2, 3, 4])

In [111]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a2[0,:]

array([0, 1, 2, 3])

In [114]:
a2[:,2]

array([ 2,  6, 10])

In [118]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [120]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [133]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [137]:
a2[1,0::3]

array([4, 7])

In [148]:
a2[0:2,1:5]

array([[1, 2, 3],
       [5, 6, 7]])

In [151]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [158]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
a3[0,1]

array([3, 4, 5])

In [168]:
a3[1,:,1]

array([10, 13, 16])

In [172]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [180]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [184]:
# iterating
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [185]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [187]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [188]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [189]:
# tranpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [190]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [193]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [194]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [198]:
# stacking
# horizental
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [200]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [201]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [202]:
# splitting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [205]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]